language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  include:
    - php: hhvm
      env:
        - HHVM_VERSION=3.3.0
    - php: hhvm
      env:
        - HHVM_VERSION=3.2.0
    - php: hhvm
      env:
        - HHVM_VERSION=3.1.0
    - php: hhvm
      env:
        - HHVM_NIGHTLY=1
        
before_script:
  - if [ "" != "$HHVM_VERSION" ]; then
      wget http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/hhvm_$HHVM_VERSION~precise_amd64.deb;
      sudo apt-get update;
      sudo apt-get install libstdc++6;
      sudo dpkg -i hhvm_$HHVM_VERSION~precise_amd64.deb;
    fi;
  - if [ "" != "$HHVM_NIGHTLY" ]; then
      sudo add-apt-repository ppa:mapnik/boost;
      wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -;
      echo deb http://dl.hhvm.com/ubuntu precise main | sudo tee /etc/apt/sources.list.d/hhvm.list;
      sudo apt-get update;
      sudo apt-get install hhvm-nightly;
    fi;
  - php --version

script:
  - php true_false.php
