language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  include:
    - php: hhvm
      env:
        - HHVM_VERSION=3.3.0
    - php: hhvm
      env:
        - HHVM_VERSION=3.2.0
    - php: hhvm
      env:
        - HHVM_VERSION=3.1.0
        
before_script:
  - if [ "" != "$HHVM_VERSION" ]; then
      wget http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/hhvm_$HHVM_VERSION~precise_amd64.deb;
      sudo dpkg -i hhvm_$HHVM_VERSION~precise_amd64.deb;
    fi;
  - php --version

script:
  - php true_false.php
